[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
# FIX: changed ${PORT} -> $PORT
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
WEB_CONCURRENCY = "1"
MAX_WORKERS = "1"
GRPC_ENABLE_FORK_SUPPORT = "False"
GRPC_POLL_STRATEGY = "poll"
GRPC_MAX_IO_THREADS = "1"
