[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
# Run via Python so PORT is handled inside main.py
startCommand = "python main.py"

[variables]
WEB_CONCURRENCY = "1"
MAX_WORKERS = "1"
GRPC_ENABLE_FORK_SUPPORT = "False"
GRPC_POLL_STRATEGY = "poll"
GRPC_MAX_IO_THREADS = "1"

# Increase timeouts
REQUEST_TIMEOUT=30
KEEP_ALIVE_TIMEOUT=75

# Optimize for voice processing
MAX_AUDIO_SIZE=10485760  # 10MB
MIN_AUDIO_SIZE=5000      # 5KB

# Better error handling
PYTHONUNBUFFERED=1