[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
# Run via Python so PORT is handled inside main.py
startCommand = "python main.py"

[variables]
WEB_CONCURRENCY = "1"
MAX_WORKERS = "1"
GRPC_ENABLE_FORK_SUPPORT = "False"
GRPC_POLL_STRATEGY = "poll"
GRPC_MAX_IO_THREADS = "1"
